### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by andreanardi** [Tinkoff/gatling-kafka-plugin#126]
Hi, when will the new version with Java support be released?

**Comment by jigarkhwar** [comment]
Hello

we are planning to release for a few days 

https://github.com/Tinkoff/gatling-kafka-plugin/pull/125

**Comment by jigarkhwar** [comment]
https://github.com/Tinkoff/gatling-kafka-plugin/releases/tag/v0.11.0
Try it :)
