### ISSUE TITLE
Version 0.11.2 still failing with java.io.FileNotFoundException

### ISSUE THREAD

**Issue by barryperez-sky** [Tinkoff/gatling-kafka-plugin#154]
Hi,

Sorry to keep raising issues! Doesn't look like the previous one can be re-opened.

Testing out 0.11.2, I'm still getting FileNotFoundException (as per #152) when trying to run.

Looks like the latest release still had scoverage enabled when it was built - please see full example attached with a simple gradle project and a runner for ease of use.

[java-kafka-test.zip](https://github.com/Tinkoff/gatling-kafka-plugin/files/11330946/java-kafka-test.zip)

**Comment by jigarkhwar** [comment]
sorry for my inattention 
probably new version solves the problem

**Comment by barryperez-sky** [comment]
Hi @jigarkhwar - thanks for taking a look so quickly - will try as soon as the new release appears on maven central and let you know!

**Comment by barryperez-sky** [comment]
Thank you!
