### ISSUE TITLE
Could not find artifact ru.tinkoff:gatling-kafka-plugin_2.12:jar

### ISSUE THREAD

**Issue by partheebanMani** [Tinkoff/gatling-kafka-plugin#161]
I am trying to use this plugin in my Java maven project.

I am getting error like
Could not find artifact ru.tinkoff:gatling-kafka-plugin_2.12:jar:0.12.0 in central (https://repo.maven.apache.org/maven2)

Could not find artifact org.apache.kafka:kafka-streams-scala_2.13:pom:7.4.0-ce in central (https://repo.maven.apache.org/maven2)

Could not find artifact io.confluent:kafka-streams-avro-serde:pom:7.4.0 in central (https://repo.maven.apache.org/maven2)

Could not find artifact io.confluent:kafka-avro-serializer:pom:7.4.0 in central (https://repo.maven.apache.org/maven2)

**Comment by wangjinahappy** [comment]
how to solve this problem？I meet the same problem

**Comment by partheebanMani** [comment]
Dependencies are in confluent maven. so need to include confluent maven in pom.mxl.

<repositories>
    <repository>
        <id>confluent</id>
        <url>https://packages.confluent.io/maven/</url>
    </repository>
</repositories>
